sudo: required
language: node_js
services:
- docker
node_js:
- 'node'
notifications:
  email:
  - howardc93@gmail.com
  - christian@paral.in
  - aqc2109@columbia.edu
before_install:
install: true
script:
- sudo bash scripts/build.sh
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script: scripts/postbuild.sh
