sudo: required
language: node_js
services:
- docker
- redis-server
node_js:
- 'stable'
addons:
  postgresql: "9.4"
install: true
notifications:
  email:
  - howardc93@gmail.com
  - christian@paral.in
  - aqc2109@columbia.edu
# This is an attempt to make caching work
before_script:
- docker pull yasp/yasp:latest
- docker build -t "yasp/yasp:latest" .
script:
# don't need to build since the docker image already built
- docker run -e "TEST_SKIP_BUILD=y" -e "COVERALLS_SERVICE_NAME=travis-ci" -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN --net=host -i yasp/yasp:latest (npm run test && (npm run coveralls || true))
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: k8s
  script: cluster/scripts/deploy.bash
